# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Devtools
    VERSION: String

    class Error < StandardError
    end

    def self.install!: () -> void
    def self.templates_path: () -> String
    def self.tasks_path: () -> String
  end
end
